### ISSUE TITLE
New 0 byte issue

### ISSUE THREAD

**Issue by dipunm** [jstaf/onedriver#134]
I use KeepassXC and I think I found the temporary solution to a problem I was having, and a root cause to possibly diagnose. I am happy to run tests and collect logs with some guidance.

Effectively, KeepassXC has this https://github.com/keepassxreboot/keepassxc/issues/1724 feature.

The file in nautilus shows fine, but from another device, the file is an empty 0 byte file.
There are no problems with this turned off.
I wonder if the problem is that the file is written, but then renamed before the file uploaded and therefore the rename action is different on client and server. On client, it renames a 2.8MB file, on server it renames a 0 byte file.

**Comment by dipunm** [comment]
The recommendation is to keep this option on, so as to prevent data loss in case of a catastrophic power loss situation (or eg. if my computer froze and I had to hard reset it)

This is why I'd love to see this addressed so I can re-enable it.

**Comment by jstaf** [comment]
I spent a lot of time digging into this in a previous issue (both LibreOffice and KeepassXC had the same issue where the way they like to save things followed the pattern: create temp file -> rename it to the target filename). Previously onedriver would try to upload a 0-byte file to obtain a OneDrive ID before doing any uploads (so it could track things in case the newly uploaded file got renamed). 

Anyhow, I fixed things in 0.10.0+ by just not uploading 0-byte files at all anymore for files <4MB. (It just uploads the full file and locks it so it can't be renamed until the upload is done instead of fooling around with the 0-byte files.) What version are you running?

**Comment by isvoboda** [comment]
Hi there, I am not sure if this is related, but I came across with zero-byte issue like behavior as well.

I have copied three svg files into folder mounted by `onedriver`.
Only one file got uploaded Ok, other two files were uploaded with zero-byte size to OneDrive cloud.

I am using onedriver from Arch's `aur` repo.

```
onedriver -v
onedriver v0.9.2 f560cbe4
```

I will try to upgrade to the latest stable version.

**Comment by dipunm** [comment]
I'm actually on 0.9.2 so I'll have to upgrade and try again

**Comment by dipunm** [comment]
@jstaf Could you elaborate on the 0 byte tracking? You said to track if the file uploading got renamed and that's what is happening here right?

**Comment by dipunm** [comment]
I've asked @fmoledina to update the package on archrepo :)

**Comment by jstaf** [comment]
OneDrive only gives a file an ID after it's been uploaded. Files that don't have an ID cannot be moved/renamed safely because there's nothing to rename on the OneDrive servers (attempting to rename objects using their path is really unsafe because nothing guarantees that you've got the right file at that path). In onedriver versions < 0.10 we would upload a 0-byte file to in order to obtain an ID in case we needed to do renames and other similar operations while the file was still being uploaded in the background.

However, LibreOffice and KeepassXC would not only save their contents to a temp file before renaming it, they would also create a temp file in the final destination name to check that they could write to that path at all. There was a race condition where depending on which temp file "got there first" (either the "can I save here?" tempfile or the "actual data" file) you could end up with the 0-byte ID placeholder file still being kept. Microsoft also does some stuff on their side in the background once you upload a file, and it was unclear if this played an impact as well. 

The fix was to not do the 0-byte placeholder file stuff anymore for small files <4MB. It still happens for files >4MB (otherwise we'd need to wait for the full upload to complete the first time you save a file there, which could cause whatever program you're using to "freeze" until the initial upload is finished), but I'm open to changing that if people run into this issue again on larger files. 

Anyhow, the whole situation is covered by this test case here now: https://github.com/jstaf/onedriver/blob/master/fs/fs_test.go#L474-L501. I should probably extend this test case to try out LibreOffice on a file >4MB as well here just to be on the extra safe side. (The "magic 4MB limit" is the size cutoff for doing more complex multipart uploads designed for larger files.)

**Comment by dipunm** [comment]
Thanks for the explanation, it was clearly not an easy problem.

**Comment by jstaf** [comment]
@dipunm Yes please on the new issue :slightly_smiling_face:

**Comment by jstaf** [comment]
I did some additional testing on this and there was an edge case where you could still get 0-byte files from LibreOffice/KeepassX's save pattern when saving files >4MB. Anyhow, I've rewritten how uploads work to avoid this, although it comes as a bit of a performance impact for these apps. However this performance impact is probably a bit safer in the long run and gives better feedback on what's happening (less guessing if a file has been uploaded in the background by onedriver... it immediately uploads a file the first time it is saved).

Anyhow, fixed in master, going to close this. (0-byte files don't get used anymore for anything unless you create one manually.)
