### ISSUE TITLE
What about the GPG requirement to install OneDriver on LInux?

### ISSUE THREAD

**Issue by kenblood** [jstaf/onedriver#149]
During installation on MXLinux (debian base) got stopped by a problem with my GPG keyring.    I haven't needed to install GPG yet, so don't have keyring setup, and don't know Jeff Stafford's public key.   I'll install gpg.    Can anybody give me Jeff's public key?

**Comment by jstaf** [comment]
https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x32B0465E0489465971D33FC822C4AB3E4B9A80AE

You don't actually need the GPG key - been awhile since I used Debian-related distros, but you should just be able to install the .deb [directly from the PPA](https://launchpad.net/~jstaf/+archive/ubuntu/onedriver/+files/onedriver_0.11.1-1_amd64.deb) (if it's not working out via apt), or compile it from source and install that way. You can even make the .deb yourself by following the instructions in [README.md](https://github.com/jstaf/onedriver#installation-from-source).

**Comment by jstaf** [comment]
I'm going to close this since I think this has been answered. Please reopen if you're still having issues.
