### ISSUE TITLE
Custom cache location

### ISSUE THREAD

**Issue by bayazidbh** [jstaf/onedriver#164]
This is a great tool, but not long after I started using it, I noticed that around 10 GB was gone from my main `/` drive. I use a rather small 250GB SSD for `/` and then a 4TB HDD in several partitions at `/media/`, 10GB is rather noticeable now that half of the SSD is filled.

It would be nice to be able to point to a custom cache location. I tried setting up a symlink from `~/.config/onedriver/` to a directory in `/media/data` hardisk, but it seems to cause mounting to stuck in a fail loop.

Would it be possible to either allow following symlink for cache location or natively allow and set custom caching location?

**Comment by jstaf** [comment]
Yes you can change the cache location using the `-c` option. Since the GUI launches the filesystem via systemd, you'll need to update the systemd unit configuration to use the new location. You can make this configuration change via `systemctl edit --user onedriver@.service`. It will open a text editor- just add the following text (this example would put the cache directory under `/media/data/onedriver`):

```
[Service]
ExecStart=
ExecStart=/usr/bin/onedriver -c "/media/data/onedriver/%i" %f
```

Once you edit the file, move the existing cache directory to the new location via `mv ~/.cache/onedriver /media/data`. This is only necessary if you want to keep the cached files, otherwise you can skip this step and just delete the cached data via `onedriver --wipe-cache`. 

After you've edited the systemd unit (and optionally moved the existing cache to the new location), just restart the filesystem and it will use the new cache location. Let me know if you have issues with this process!

(I'll leave this issue open as a note to make the cache directory configurable using the GUI in the next release.)

**Comment by bayazidbh** [comment]
Thank you for the explanation. WIll use the systemd method, but looking forward to the next release.

**Comment by bayazidbh** [comment]
> (I'll leave this issue open as a note to make the cache directory configurable using the GUI in the next release.)

Hey, I just noticed a new release, though I don't notice any GUI way of changing/moving cache directory? While I'm fine with the current implementation and don't mind, can I ask if there's a progress or new milestone for the feature? Thanks!

**Comment by jstaf** [comment]
Honestly, the reason was that I wanted to have a yaml configuration file that's shared between the `onedriver-launcher` GUI + the filesystem itself for saving settings. I briefly looked into doing it in C/libyaml (which would have been required since the GUI is in C), got intimidated, and am just going to rewrite the GUI in Go since it'll be 10x easier for me to do that way: https://github.com/jstaf/onedriver/issues/212

**Comment by jstaf** [comment]
This is supported now in the UI. Sorry about the wait :wink:
