### ISSUE TITLE
full, non-selective sync

### ISSUE THREAD

**Issue by norave** [jstaf/onedriver#166]
I want sync all files from a specific onedrive folder (by realtime 2 way sync). then I share it over the local network for access from different computers. I need to disable selective file synchronization (when using), otherwise onedrive does not download my data from the cloud to the local network (when i make changes in webversion)

is there any solution? first day on Linux

**Comment by abraunegg** [comment]
@norave 
> I want sync all files from a specific onedrive folder (by realtime 2 way sync).

To 'sync' your files from a specific folder in a 2-way sync fashion to your local file system (so that you can share over the local network), you may need to investigate https://github.com/abraunegg/onedrive and utilise `--single-directory` 

For more details refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-selective-directory-sync

**Comment by jstaf** [comment]
Onedriver does a "full sync" by default, and though remote change changes aren't instantaneous, it's pretty close (it picks up changes within 30 seconds). No configuration is necessary, onedriver will work to access all of your files out of the box without any additional configuration. 

(You are on your own if you try to setup a network share with the stuff from onedriver, but there's no reason it shouldn't work. I don't really understand why you would want to setup a network share for OneDrive when you could just connect all of the computers to OneDrive directly.)

**Comment by norave** [comment]
I use one energy efficient server to synchronize music projects through NAT. The rest of the computers sleep and, when turned on, automatically reload projects from the server, which is faster than my unstable internet. I do not work alone, when I come to all projects already on my computer. putting vandrive on every computer is not a good idea. then you have to wait a long time for synchronization and in this case you will have to keep all the computers on. in the case of onedriver, the files in the mounted disk are synchronized only on request (you need to click to download) and the program for synchronization (just does not see the changes from the web version of onedrive, which I initially reported

**Comment by norave** [comment]
I have a 300gb disk, but my onedrive is almost 5tb full. ondriver is apparently mounted as files on-demand, all files are displayed, but downloaded when clicked. in this case, "unison" simply does not see the change from the onedrive web interface. it detects them if you manually click on a folder or file in a directory. actually my question was: is it possible to download a specific folder completely (not on demand) so that you don't have to click every time there are changes in it?

**Comment by norave** [comment]
> @norave
> 
> > I want sync all files from a specific onedrive folder (by realtime 2 way sync).
> 
> To 'sync' your files from a specific folder in a 2-way sync fashion to your local file system (so that you can share over the local network), you may need to investigate https://github.com/abraunegg/onedrive and utilise `--single-directory`
> 
> For more details refer to: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-selective-directory-sync

ok, i try it. it looks like there is no other way

**Comment by jstaf** [comment]
> actually my question was: is it possible to download a specific folder completely (not on demand) so that you don't have to click every time there are changes in it?

Your folders are getting "synced" completely, it's just that the way unison is detecting file changes is defective. Unison is using inotify to detect file changes which means its waiting for the kernel to tell it about filesystem events that are happening to the files its monitoring. The kernel will only tell inotify that something has happened when a local change occurs (ie. something you did on your local machine). Inotify (and unison, by extension) will never pick up the remote file changes because making a change in the OneDrive web UI doesn't actually result in any syscalls on your local machine for the kernel to report to inotify as "file changes". Unfortunately there's no method in the FUSE API for us to tell inotify about remote changes either, so even if we wanted to tell unison/inotify about a remote change, we couldn't.

Use a sync client for this like rclone or abraunegg/onedrive instead. Unison will never be able to properly sync changes from onedriver because the way it detects changes has no way of detecting changes that don't involve the local machine's kernel.
