### ISSUE TITLE
[REQUEST] Tray icon

### ISSUE THREAD

**Issue by felipgab** [jstaf/onedriver#169]
Hello! The app is great and I have been using it without problems. I can even open my OneNote files with an OneNote desktop client. However, I think it would be nice if it was some kind of support for tray icons to control the mounting and show the  syncing status, like Megasync or this extension here (https://github.com/dbazza/oneDrive) for abraunegg client.

**Comment by jstaf** [comment]
This isn't a sync client, no syncing is happening back and forth. A better way to think about it is that the filesystem is doing on-demand downloads of your files when you click on them (and then it keeps copies locally just in case you need them later). 

If the drive is mounted, it is "in sync" - there is no sync status to show. (Going to close this one because there's no status to show with a tray icon)
