### ISSUE TITLE
Errors in RedHat 7 install

### ISSUE THREAD

**Issue by wwnetwrk** [jstaf/onedriver#185]
When trying to install this on RedHat 7, we get the error [Errno socket error][SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c.618). This is after installing dnf and enabling copr. How can we get around this?

**Comment by wwnetwrk** [comment]
Can we get this re-opened?

**Comment by jstaf** [comment]
I did some further looking into this tonight and after some serious head-scratching I figured out why there wasn't an EL7 build until now - it turns out that systemd's user sessions are completely disabled in EL7: https://bugs.centos.org/view.php?id=8767

This breaks most of the actual onedriver RPM package - the GUI sessions rely on systemd user sessions to run the filesystem as normal (non-root) users. Likewise, enabling the filesystem between boots via the CLI also relies on starting a systemd user unit as the user who's mounted the filesystem. I'm removing the EL7 packages because neither of these workflows will work properly without systemd user sessions.

---

If you are interested in using onedriver on EL7, the actual filesystem itself *does* work, but the tooling that supports mount persistence between boots/GUI (systemd user sessions) does not. The filesystem binary is all you need if you want to run on CentOS 7.

You can compile and use the filesystem on CentOS 7 via the following:

```
yum install epel-release
yum install gcc pkgconfig webkitgtk4-devel
go build

# mount the filesystem
./onedriver path/to/mountpoint

# you can also copy around the "onedriver" binary to your other centos7 hosts -
# the only runtime dependency is webkitgtk4
```

**Comment by abraunegg** [comment]
@jstaf 
> If you are interested in using onedriver on EL7, the actual filesystem itself does work, but the tooling that supports mount persistence between boots/GUI (systemd user sessions) does not. 

Whilst `--user` is not supported for CentOS etc, this method *does* work for starting a specific service as a particular user:
```
systemctl enable <servicename>@<username>.service
```

See: https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#onedrive-service-running-as-a-non-root-user-via-systemd-all-linux-distributions

The '@' service file contents example:
```
[Unit]
Description=OneDrive Free Client for %i
Documentation=https://github.com/abraunegg/onedrive
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=@prefix@/bin/onedrive --monitor --confdir=/home/%i/.config/onedrive
User=%i
Group=users
Restart=on-failure
RestartSec=3
RestartPreventExitStatus=3

[Install]
WantedBy=multi-user.target
```

I have not investigated if this will work for 'onedriver' however

**Comment by jstaf** [comment]
Yes, but then the GUI needs to run as root+change which dbus bus the GUI connect tos+rewrites for all of the other distros (since we currently use the same technique to determine the mountpoint, not which user it runs under). 

I may revisit this when looking into Flatpak packaging (it would nice to not be tied to systemd, but would need another way of launching processes at boot that was cross-distro + also maybe mac/BSD).
