### ISSUE TITLE
Unable to login to work account

### ISSUE THREAD

**Issue by vikasrawal** [jstaf/onedriver#193]
I am unable to login to my work account using onedriver. On the onedrive web interface, I can see an "unsuccessful sign-in" using "safari" browser. I am running Manjaro and there is no safari on Manjaro. I get no error in onedriver, and the browser window just vanishes once I enter my work account credentials.

**Comment by vikasrawal** [comment]
When I try from the commandline, I get this:

INFO[2021-11-03T11:36:51]main.go:99 000001:main.main() onedriver v0.12.0 16a4cc37
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
FATA[2021-11-03T11:37:19]oauth2_gtk.go:32 000001:fs/graph.getAuthCode() No validation code returned, or code was invalid. Please restart the application and try again.

**Comment by jstaf** [comment]
It likely says Safari because we're using the embedded WebKit browser for the authentication window (you can read more about it here: https://webkit.org/).

```
No validation code returned, or code was invalid. Please restart the application and try again.
```

^ this indicates that signing in was unsuccessful. Likely your password was wrong or other authentication failed (make sure you use your full email for the username). If you want, you can try authenticating via the headless version (see README). This will let you try out authentication via a normal browser if you want.

(Basically the way authentication works for OneDrive is you login in a web browser and upon success, it redirects you to a URL with `code=` in it. The part following the `code=` is a key that allows onedriver to obtain the actual authentication tokens that are used by the program. If there's no part with `code=` in it, it means authentication has failed.)

**Comment by Oxalin** [comment]
@vikasrawal Was this ever solved or this issue still valid?

**Comment by jstaf** [comment]
Guessing this got fixed when OP tried again and/or sometimes Microsoft likes to be edgy and tell you why the login failed in the redirect URL, see https://github.com/jstaf/onedriver/issues/302#issuecomment-1316116015 as an example. Going to close this since OP hasn't updated the issue for 2 years lol
