### ISSUE TITLE
Linux CLI-only setup

### ISSUE THREAD

**Issue by rcarmo** [jstaf/onedriver#20]
Hi there!

I'd like to leave an "anti-request" here, since I would like to be able to use the Linux client without a GUI (or X, or anything else) and right now authorisation is hard-coded with an `#ifdef(__linux__)` to pop up a browser. 

Could there be an option (build or run time) not to use WebKitGTK at all?

**Comment by jstaf** [comment]
Hah, an anti-request is still a feature! It'll likely need to be a build-time option, otherwise the compiled binary will get linked against WebKitGTK and require it as a dependency. I'll see what I can do to add that in. 

Just as a heads up - it may be some time before this is implemented- my current dev priority is getting onedriver to sync server-side changes to the local client. In the meantime, you can delete the contents of the`#ifdef(__linux__)` sections from graph/oauth2_gtk.c and it will produce a GUI-free binary.

**Comment by jstaf** [comment]
Hey @rcarmo, I've rewritten things so that you can exclude WebKitGTK from the build by disabling CGo. If you build onedriver with `CGO_ENABLED=0 go build`, onedriver will be built without the popup browser (all of the C dependencies like WebKitGTK and X11 won't be required at runtime either this way).

Closed by #27

**Comment by pepa65** [comment]
This would be great to document, as it greatly simplifies the CLI-only build:
```
cd cmd/onedriver
CGO_ENABLED=0 go build
sudo cp onedriver onedriver_cli /usr/local/bin/
```

I am not sure how to configure a drive instance though...

**Comment by jstaf** [comment]
It's no longer documented because you can just use `--no-browser` option to authenticate from the CLI with the normal build. See the readme on setting up new drives - you can just do `onedriver /path/to/mount`, or alternatively use systemd to mount things automatically for you (see the readme).

**Comment by pepa65** [comment]
But it's nice not to have to install X and all kinds of packages that you don't need. Can I use the go binary build somewhere else and will it work on a headless system if I use `--no-browser`?
