### ISSUE TITLE
 OpenSUSE Build Service contain only .deb for Debian or .deb for XUbuntu (not Ubuntu)

### ISSUE THREAD

**Issue by orbitalchicken** [jstaf/onedriver#258]
"OpenSUSE Build Service" contain only .deb for Debian and .deb for XUbuntu (not Ubuntu)
These is no .DEB for Ubuntu (or Linux Mint)
Could you please provide a real .DEB for Ubuntu? Thank you.

**Comment by jstaf** [comment]
Those are the "real" .debs for Ubuntu. Don't ask me why but they added an "x" in front of all the official Ubuntu build environments on the OpenSUSE Build Service. It's not because it's for Xubuntu, it's just the name of the build chroot on the build service. (But even if it was, Xubuntu shares the same set of packages as "normal" Ubuntu so the .debs built there are equivalent.)

If you're feeling paranoid though, you can always build a .deb yourself for whatever distribution you want (see the readme on the front page).
