### ISSUE TITLE
Onedriver filling syslog at the speed of light

### ISSUE THREAD

**Issue by krptg0** [jstaf/onedriver#270]
Hi,

Thanks for the awesome work :)

Since installation, onedriver borgs up syslog, making it as big as 15Gb in only 3 days.
Syslog is  full of these kind of lines : 

```
Jul 27 14:58:18 hostname onedriver[2198]: #033[90m14:58:18#033[0m #033[33mDBG#033[0m  #033[36mop=#033[0mStatFs
Jul 27 14:58:19 hostnameonedriver[2198]: #033[90m14:58:19#033[0m #033[32mINF#033[0m Fetched 0 deltas.
Jul 27 14:58:19 hostname onedriver[2198]: #033[90m14:58:19#033[0m #033[33mDBG#033[0m Serializing cache metadata to disk.
Jul 27 14:58:20 hostnameonedriver[2198]: #033[90m14:58:20#033[0m #033[33mDBG#033[0m  #033[36mop=#033[0mStatFs
Jul 27 14:58:22 hostname onedriver[2198]: #033[90m14:58:22#033[0m #033[33mDBG#033[0m  #033[36mop=#033[0mStatFs
```

Is there something to do to limit its verbosity ? Thanks in advance,

**Comment by jstaf** [comment]
Change the log level to warn or info (there is a `--log` option). Follow the directions here re: `systemctl edit` https://github.com/jstaf/onedriver/issues/164#issuecomment-903293098, but instead of the custom cache location just add the log optino

```
# setting the log level to warn
[Service]
ExecStart=
ExecStart=/usr/bin/onedriver --log warn %f
```

The log level is roughly the following:

* trace - absolutely everything
* debug (default) - logs the bigger file ops like reads/writes/readdir
* info - uploads and downloads
* warn - stuff that might have gone wrong
* error - stuff that definitely is a problem
* fatal - only log errors that kill the program

Hoping to make this easier to configure in the next version.
