### ISSUE TITLE
Suggestion: Daemon Architecture for Background Syncs

### ISSUE THREAD

**Issue by sbaeurle** [jstaf/onedriver#29]
At first I need to admit I really like the concept of using OneDrive as a Drive Mount in you file system.
Yet I think a pure online usage of OneDrive is not always possible and some offline caching mechanisms should be implemented.
During my tests I encountered some problems with the file system encountering crashes or beeing quite unresponsive due to nonexistent or slow network connections.
Resulting these crashes, I often needed to restart the application and "resync" my OneDrive files.
During these rebuilds of the mount structure, no cache was used to speed up the process.

Therefore I would suggest a new architectural approach to the application.
In order to enable consistent caching as well as autostart possibilities to the application you should consider splitting up the application into two seperate processes.

Process 1 handles all user and UI related tasks and provide the desired configuration.
Process 2 (the daemon) handles the synchronisation and caching of the onedrive mount.

The daemon process could be initialized and controlled by the OSs Init-System (like systemd) and provide convenient and fault tolerant access to the onedrive mount.

I'm looking forward to hear you opinion on my suggestion.

**Comment by jstaf** [comment]
For syncing in a background thread - Check out the `delta` branch. There is a new background thread that periodically polls the server for updates and applies server-side changes to your local state. It's not ready for use yet (currently sorting out how to properly reconcile files changed on both the server and the local client without losing data), but that's going to be the main feature in the next update. 

Re: unresponsiveness when there's no/slow network - I haven't implemented timeouts and stuff like that yet. Ideally, onedriver should timeout an op rather than leave you hanging indefinitely if the network goes out. I'll see what I can do there to improve the experience for slow network connections.

For offline usage - that'll need to come in a later update. Currently the contents of files are cached on disk, but not the metadata used to identify them. The goal I'm shooting for right now is something akin to GNOME's GVFS backend for Google Drive (something that lets you access your files when you're online). Anyhow, I'm not saying offline usage isn't happening, I just need to finish the basic functionality for online usage before I start looking into the offline stuff.

**Comment by jstaf** [comment]
Hey @sbaeurle I think this should be completely implemented now:

* There's now a background thread that periodically updates your local state.
* The filesystem works in read-only mode while you're offline.
* The filesystem will alternate between offline mode and online mode depending on if you have an internet connection or not.
* There's a timeout (15s?) for requests if your network connection disappears.
* There's the ability to autostart the filesystem using systemd (see the readme on the main page for instructions on how to use it).

Let me know if you notice any other issues!
