### ISSUE TITLE
Donate crypto?

### ISSUE THREAD

**Issue by Musickiller** [jstaf/onedriver#292]
Hi!

Would you consider adding a few crypto addresses to docs/donate.md? It's not like I personally can donate a lot, but I think it's a nice touch to have those!

If you don't fancy crypto yourself, you can still have some remote multiwallet with all kinds of coins for no time/effort/money cost at all. And if you add Nano (XNO) or Monero (XMR), I'll happily send you a buck or two for the effort it will take you to setup stuff and then get the money into whatever currency you need back in the real =D

And hopefully it won't be for naught! 😂

Kind Regards,
Dmitrii

**Comment by jstaf** [comment]
Hi Dmitrii, thank you but I don't have any plans to accept crypto at the moment (based on prior experience setting up new donation methods is actually a ton of work due to paperwork/stuff that needs to be setup). Probably the best way to donate is to convert crypto into the currency of your choice and donate through Github Sponsors. Thank you!
