### ISSUE TITLE
Education accounts

### ISSUE THREAD

**Issue by liujilei156231** [jstaf/onedriver#302]
Does ``OneDriver`` support education account login?

When I logged into my school education account, nothing happened. (I'm sure there is no problem with my account password.)

**Comment by jstaf** [comment]
Try running `onedriver /path/to/some/folder` and logging in with your education acccount. This will print any logs with any errors to the console.

**Comment by liujilei156231** [comment]
When I enter the password, I am prompted with the following information.
![image](https://user-images.githubusercontent.com/62644866/201955067-45ec75dc-ebef-4322-9ed8-1d6fb291e567.png)

**Comment by jstaf** [comment]
Hmmm, did you log in successfully? This is usually what happens when authentication does not successfully complete (sometimes there are restrictions on third-party apps like this one).

You can try `onedriver --no-browser /home/liu/Desktop/onedrive_tmu/` to try logging in using a normal web browser. (It will give you a link to go to, just complete the login, and then paste the final URL in the terminal.) If this set of instructions doesn't work, then the problem is that the login itself is failing (either wrong credentials or there is something non-standard/restrictions on your organizations account).

**Comment by liujilei156231** [comment]
```
(base) liu@liu:~/Desktop$ onedriver --no-browser /home/liu/Desktop/onedrive_tmu/
08:54:39 INF onedriver v0.13.0 b96e638d
Please visit the following URL:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=3470c3fa-bc10-45ab-a0a9-2d30836485d1&scope=user.read%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf

Please enter the redirect URL once you are redirected to a blank page (after "Let this app access your info?"):
```

then I get a link on the browser

```https://login.live.com/oauth20_desktop.srf?error=invalid_client&error_description=AADSTS650051%3a+Using+application+%27onedriver%27+is+currently+not+supported+for+your+organization+tmu.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+tmu.edu.cn+before+the+application+onedriver+can+be+provisioned.%0d%0aTrace+ID%3a+ad3f0010-8e4e-4e5a-81b0-ca202823dc01%0d%0aCorrelation+ID%3a+7bbcbd9b-655e-46ce-a559-e9ed7b2aaa96%0d%0aTimestamp%3a+2022-11-16+00%3a55%3a13Z#```

This looks like an issue with my account. I will consult my agency.
Thank you !
