### ISSUE TITLE
[Question] Bidirectional sync

### ISSUE THREAD

**Issue by FerLuisxd** [jstaf/onedriver#315]
1) How does Bidirectional sync actually work?
Is it a webhook that always listens to changes?
Is it a request that happens every X seconds, can it be modified?

2) Is there a way to sync only one directory from onedrive?

Thanks!

**Comment by abraunegg** [comment]
@FerLuisxd 
The 'onedriver' client implements a native file system that only provides the OneDrive 'on-demand' functionality. As such, its not technically a 'sync' client, but an 'on-access | on-demand' client for your data.

For a 'sync' client, that performs bidirectionally, provides capability for webhooks, provides a provision to only sync a single directory you need to look at 'onedrive' - https://github.com/abraunegg/onedrive

**Comment by jstaf** [comment]
1. The bidirectional sync works the same way as the abraunegg client - both apps poll an endpoint at Microsoft that has a list of changes since the app last connected (this client checks every 30s - this is not configurable). The abraunegg/onedrive client downloads all changed files, all the time. This downloads changes if they are in the file you are accessing (as you access it).
2. No. All directories are "synced" all the time, even if they are not downloaded yet. You will always have the most recent version of the file as long as you are connected to the internet. Don't want to sync a directory/file? Don't open it. Just by using the app you have setup a selective sync of only the files you actually use without having to configure a thing.

The main difference between the different onedrive clients is that this one (onedriver) is a bit easier to use and nicer on your internet bandwidth. The abraunegg/onedrive client has the advantage of being able to access Sharepoint and shared items. There's also rclone, but it is unable to do bidirectional sync at all. Pick whichever tool suits your needs best.

**Comment by isokissa** [comment]
Additional question: in windows OneDrive it is possible to free the space on local hard drive by saying that you want certain file/folder to be available only in cloud. Is this possible to do with onedriver?
