### ISSUE TITLE
Hope to support Onedrive for Business

### ISSUE THREAD

**Issue by ToWarmth** [jstaf/onedriver#324]
When I login account of Onedrive for Business,it doesn't work. No mountpoint was made,nothing happened. Really hope this can support Onedrive for Business.

**Comment by zany130** [comment]
see https://github.com/jstaf/onedriver/issues/304

**Comment by chenxiex** [comment]
It seems to support my Onedrive for Business (edu).

**Comment by jstaf** [comment]
This software has always supported OneDrive for Business (in fact it's what I normally dev against since that's what Microsoft provides for dev accounts). Usually when this happens (and you got the login popup), the issue is that there's some weird restriction on your organization or other issue similar to this one: https://github.com/jstaf/onedriver/issues/302 (the error is frequently included in the URL Microsoft gives you on login).
