### ISSUE TITLE
Trash handling in Nautilus

### ISSUE THREAD

**Issue by LiohMoeller** [jstaf/onedriver#33]
When I delete a file from the mounted directory e.g. using the rm command it is successfully transferred to the OneDrive Trash. Trying to delete a file using the Nautilis filemanager results in a warning message like: trash folder cannot be found or created. Still the file is moved to the OneDrive trash with an additional folder .Trash-1000.

Additionally it would be nice to be able to access the OneDrive Trashbin using the onedriver application.

**Comment by jstaf** [comment]
Hah, I'm surprised I haven't run into this bug yet. Good catch. 

I'll see if I can have both the trash folder creation / Nautilus trash bug fixed as well as the OneDrive Trash fixed in the next release.

**Comment by jstaf** [comment]
Just an update on this: after initial investigation, there currently is no documentation on how to access or manipulate the OneDrive trash via the API - I've filed a bug report on the OneDrive documentation here: https://github.com/OneDrive/onedrive-api-docs/issues/1212

Using the OneDrive trash directly will have to wait until that issue gets addressed by Microsoft. However, I should have the normal Linux filesystem trash working for the next release (since Linux just stores things as plain-old files under `/.Trash-1000/`).

**Comment by jstaf** [comment]
Hi @LiohMoeller I think this should be fixed in the latest onedriver version. You should be able to trash and restore files on OneDrive now through onedriver. Please reopen this issue if you notice any issues with the new functionality.

Microsoft has indicated that there's actually no API I can use to access the Recycle Bin server-side yet, so the plain-old trash in Nautilus will have to do for now.

**Comment by LiohMoeller** [comment]
Works perfectly, Thanks a lot!
