### ISSUE TITLE
Move to webkitgtk-4.1

### ISSUE THREAD

**Issue by foopsss** [jstaf/onedriver#342]
Hello.

I've recently noticed that some distros like [Gentoo](https://bugs.gentoo.org/893668) and [Fedora](https://fedoraproject.org/wiki/Changes/libsoup_3:_Part_One#Detailed_Description) are planning to drop packages for webkitgtk-4.0, which would make building onedriver impossible AFAIK since it seems to require webkitgtk-4.0 as of 0.13.0.

According to the Gentoo bug tracker, there are no API differences between 4.0 and 4.1, but things might get messy for packages that depend on libsoup 2.4, as webkitgtk-4.1 uses libsoup3.

This is particularly worrying because Fedora seems to be ready to drop libsoup2 and packages that depend on it as early as Fedora 39 or Fedora 40, and the GNOME Gentoo Team has made significant progress towards getting rid of webkitgtk-4.0 (which my [onedriver package for Gentoo](https://github.com/foopsss/Ebuilds/tree/main/net-misc/onedriver) depends on at the moment).

Best regards,
Lucas

**Comment by foopsss** [comment]
BTW, I'd like to ask if you could make a release for v0.14.0 (in the Releases tab), as I need the source code specific to a version to make a new package for Gentoo.

I've also noticed that it seems there isn't a working 0.14.0 package for Fedora users right now, as the latest build in COPR has failed.

**Comment by jstaf** [comment]
Oh, yeah - created the 0.14.0 release just now. There is a 0.14.0 build for Fedora/COPR, it's Amazon Linux and EL8 that are broken- haven't got around to fixing those yet (most builds succeeded, but if any fail, then the build is marked as failed): 

* https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/build/6171808/
* https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/build/6174617/

Re: webkit2gtk-4.1, it works just fine with that version, I actually updated things to use it in the last release since that's what Tumbleweed has (I uninstalled Fedora in favor of OpenSUSE Tumbleweed after the latest Red Hat licensing debacle). There's a script that auto-sets which version to build against before compiling https://github.com/jstaf/onedriver/blob/master/onedriver.spec#L30. I'm going to close this issue since we officially switched to 4.1 in the latest release: https://github.com/jstaf/onedriver/blob/master/fs/graph/oauth2_gtk.go#L7

Also - thank you for being a maintainer :heart:

**Comment by foopsss** [comment]
Thanks! I'll send a PR when possible to add the Gentoo installation instructions. My package is not "official" (meaning as in available in the Portage tree) as it is hosted on my own repo, and it requires a download for a separate dependency tarball along with the source code (for the reasons described in the [Gentoo Devmanual](https://devmanual.gentoo.org/eclass-reference/go-module.eclass/index.html)), but it works just fine.
