### ISSUE TITLE
Ubuntu 23.10 missing resource file

### ISSUE THREAD

**Issue by Plarpoon** [jstaf/onedriver#373]
Hello, when manually installing onedriver on Ubuntu 23.10 (from OBS) it says that currently the repository is missing the resource file.

That unfortunately means that I am left out as an only possible option to install the compiled deb instead. This solution is unfortunately not optimal, as not having a working repository means I have to go hunt for an updated DEB file on the web and refresh the page at least twice a week to see if an update came out. Is that something that can be fixed? Are there automatically updating alternatives for Ubuntu?

Thanks in advance!

**Comment by Plarpoon** [comment]
I can see you have a resource file in the actual repo, it just doesn't seem to work. Is it possible that is because regardless of the fact that on GitHub it's written that is the repository for Ubuntu it's actually just for xUbuntu like written on OBS repo? Just guessing here, I have no actual clue, would like to know your opinion.

**Comment by foopsss** [comment]
OBS can make packages for Debian and Debian-based distributions, and jstaf's repo does indeed have builds for Debian, Ubuntu and Raspbian. If the repo is somehow broken you'll have to wait for jstaf to fix it.

**Comment by Plarpoon** [comment]
That's great to hear, would really love to have that repo working! Thanks!

**Comment by jstaf** [comment]
You need to upgrade your version of Ubuntu. Kubunto 21.10 is end-of-life https://news.itsfoss.com/ubuntu-21-10-eol/. If you would like to not upgrade for long periods of time, you should use Ubuntu 22.04, which is an LTS release.

There is an Ubuntu 23.10 repo, but a Ubuntu 21.10 client won't be able to find builds for 21.10 there, because it is a 23.10 repo for 23.10 clients only.
