### ISSUE TITLE
Be able to rename email string used in file managers (in particular Gnome Files sidebar) to anything else

### ISSUE THREAD

**Issue by RTSAjwad** [jstaf/onedriver#380]
[Here](https://gitlab.gnome.org/GNOME/nautilus/-/issues/3291) is an issue I was facing on Gnome Files where the sidebar was made wider to accommodate my longer email address. The folder itself is called "Onedrive" so I am unsure why the email address is used there. I am wondering if it could be possible use a different string from within onedriver instead. Maybe I could rename it to "University" or simply "Onedrive" for example. Maybe even if it just used the folder name which is also "Onedrive". It wouldn't need to be default behavior but I would find it very useful if it is possible.

**Comment by jstaf** [comment]
I actually have a WIP branch that does this here: https://github.com/jstaf/onedriver/tree/drive-rename (don't use this yet, because it will just rename things to `test drive` without giving you the option to pick).

In the meantime, just edit the file `.xdg-volume-info` at the base of the mountpoint. This is what sets the icon and mountpoint name.

**Comment by jstaf** [comment]
Done in #394
