### ISSUE TITLE
Package for Raspberry Pi 

### ISSUE THREAD

**Issue by mlongval** [jstaf/onedriver#87]
With the advent of the RPi 4 with 8 GB ram, having Onedriver run on it is realistic. 
Do you think you could build a package for it? 

Thanks

**Comment by jstaf** [comment]
Yes, though admittedly I'm a bit unfamiliar with what Rasberry Pis are actually running:

* What CPU architecture is it? x86_64, ARM, etc.
* What OS is it running? Any variant of Red Hat or Debian makes things relatively easy (I think Rasbian is basically Debian here).
* Do you want a GUI for authentication? (That's the only part that actually requires a special build and packaging.)

**Comment by mlongval** [comment]
It's ARM and running Debian. 
As for the GUI, I think just to be able to get "onedriver-headless" would be great. 

Thanks

**Comment by jstaf** [comment]
Ok, I'll see what I can do re: a more official package for ARM on Debian.

In the meantime, you can actually cross-compile the binary you need for ARM from any other computer with:

```bash
# the "CGO_ENABLED=0" is the magic part that makes the headless version with no dependencies
# if this doesn't work for some reason, try GOARCH=arm
GOARCH=arm64 GOOS=linux CGO_ENABLED=0 go build -o onedriver-headless ./cmd/onedriver
```

**Comment by jstaf** [comment]
@mlongval There is now an official package for arm64 on Debian/Ubuntu. Can you give it a try and see if it works? I can't actually verify this one since I don't have any aarch64 hardware.

Anyhow you should be able to install it via apt on the Raspberry Pi using the instructions here:

```
sudo add-apt-repository ppa:jstaf/onedriver
sudo apt update
sudo apt install onedriver
```

Alternatively I think you can actually download the package manually from the PPA here: https://launchpad.net/~jstaf/+archive/ubuntu/onedriver/+files/onedriver_0.9.1-1_arm64.deb

**Comment by mlongval** [comment]
Thanks. I will try it this weekend. Cheers!

**Comment by jstaf** [comment]
(Going to assume the new arm64 package works and will close this issue out - please reopen this issue if the new arm64 package isn't working.)
